crm/agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('agents/', AgentListView.as_view(), name='agents'),
    path('agents-create/', AgentCreateView.as_view(), name='agents-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name="agent-detail"),
    path('agent/<int:pk>/update', AgentUpdateView.as_view(), name="agent-update"),
    path('agent/<int:pk>/delete', AgentDeleteView.as_view(), name="agent-delete"),
]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import Home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('leads.urls', namespace='leads')),
    path('', include('agents.urls', namespace='agents')),
    path('', Home.as_view(), name="home"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


 

crm/leads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .views import LeadList, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, SignupView

app_name = 'leads'

urlpatterns = [

    # JSON Response


    path('leads/', views.leads, name="leads"),
    path('newlead/', views.newlead, name="newlead"),
    path('leads/<int:pk>', views.lead_details, name="lead-details"),
    path('leads/<int:pk>/update', views.lead_update, name="lead-update"),
    path('leads/<int:pk>/delete', views.lead_delete, name="lead-delete"),
    
    # Template views


    ### FUNCTIONAL ROUTES

    # path('all/', views.all, name="all"),
    # path('lead/<int:pk>', views.eachlead, name="eachlead"),
    # path('lead/<int:pk>/update', views.update_lead, name="update_lead"),
    # path('lead/<int:pk>/delete', views.delete_lead, name="delete_lead"),
    # path('create_lead/', views.create_lead, name="create_lead"),

    path('all/', LeadList.as_view(), name="all"),
    path('lead/<int:pk>', LeadDetailView.as_view(), name="eachlead"),
    path('lead/<int:pk>/update', LeadUpdateView.as_view(), name="update_lead"),
    path('lead/<int:pk>/delete', LeadDeleteView.as_view(), name="delete_lead"),
    path('create-lead/', LeadCreateView.as_view(), name="create-lead"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('signup', SignupView.as_view(), name="signup")
]

crm/agents/models.py
from django.db import models

# Create your models here.

crm/leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    is_company = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username


class Lead(models.Model):
    lead_status = (
        ('Potential', 'Potential'),
        ('Prospect', 'Prospect'),
        ('Negotiation', 'Negotiation'),
        ('Converted', 'Converted'),
        ('Failed', 'Failed')
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField(default=0)
    city = models.CharField(max_length=25, null=True)
    country = models.CharField(max_length=30, null=True)
    email = models.EmailField(max_length=50, null=True)
    agent = models.ForeignKey('Agent', on_delete=models.SET_NULL, null=True, blank=True)
    company = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=False)
    status = models.CharField(max_length=15, choices=lead_status, null=True)
    avatar = models.ImageField(null=True, upload_to='media')

    def __str__(self):
        return self.first_name


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=False)
    
    def __str__(self):
        return self.user.username


class LeadDetail(models.Model):
    Lead = models.ForeignKey(Lead, on_delete=models.CASCADE)
    files = models.FileField(blank=True, upload_to='media')
    tasks = models.TextField(max_length=1000)

    def __str__(self):
        return self.Lead.first_name


def post_user_created(sender, instance, created, **kwargs):
    print(instance, created)
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created, sender=User)

crm/agents/forms.py
from django import forms
from leads.models import Agent

class AgentCreate(forms.ModelForm):
    class Meta:
        model = Agent
        fields = (
            'user',
        )

crm/leads/forms.py
from django import forms
from .models import Lead, LeadDetail, User
from django.contrib.auth.forms import UserCreationForm, UsernameField

# class LeadForm(forms.Form):
#     first_name = forms.CharField(max_length=50)
#     last_name = forms.CharField(max_length=50)
#     age = forms.IntegerField(min_value=0)
#     city = forms.CharField(max_length=25)
#     country = forms.CharField(max_length=30)
#     email = forms.EmailField(max_length=50)
#     agent = forms.CharField(max_length=50, required=False)
#     status = forms.CharField(max_length=15)
#     avatar = forms.ImageField()

class LeadForm(forms.ModelForm):
    class Meta: 
        model = Lead
        fields = '__all__'
           

class LeadDetailForm(forms.ModelForm):
    class Meta: 
        model = LeadDetail
        fields = '__all__'

# (
#     'first_name',
#     'last_name',
#     'age',
#     'city',
#     'country',
#     'email',
#     'agent',
#     'status',
#     'avatar',
# )


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField}

crm/agents/views.py
from django.shortcuts import render, redirect, reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from .forms import AgentCreate
from .mixins import UnauthRequiredMixin

# Create your views here.
class AgentListView(UnauthRequiredMixin, generic.ListView):
    template_name = 'agents.html'
    
    def get_queryset(self):
        company = self.request.user.userprofile
        return Agent.objects.filter(company=company)


class AgentCreateView(UnauthRequiredMixin, generic.CreateView):
    template_name = 'agentcreate.html'
    form_class = AgentCreate

    def get_success_url(self):
        return reverse('agents:agents')

    def form_valid(self, form):
        agent = form.save(commit=False)
        agent.company = self.request.user.userprofile
        agent.save()
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(UnauthRequiredMixin, generic.DetailView):
    template_name = 'agentdetail.html'

    def get_queryset(self):
        company = self.request.user.userprofile
        return Agent.objects.filter(company=company)

class AgentUpdateView(UnauthRequiredMixin, generic.UpdateView):
    template_name = 'agentupdate.html'
    form_class = AgentCreate

    def get_success_url(self):
        return reverse('agents:agents')

    def get_queryset(self):
        company = self.request.user.userprofile
        return Agent.objects.filter(company=company)

class AgentDeleteView(UnauthRequiredMixin, generic.DeleteView):
    template_name = 'agentdelete.html'

    def get_queryset(self):
        company = self.request.user.userprofile
        return Agent.objects.filter(company=company)

    def get_success_url(self):
        # return "/all"
        return reverse("agents:agents")

crm/leads/views.py
import json
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .serializers import LeadSerializer
from .forms import LeadForm, LeadDetailForm, CustomUserCreationForm
from .models import User, Lead, Agent, LeadDetail


# Create your views here.

#######################
#### Json Response ####
#######################


@csrf_exempt
def leads(request):
    lead_list = Lead.objects.all()
    serializer  = LeadSerializer(lead_list, many=True)
    return JsonResponse(serializer.data, safe = False)

@csrf_exempt
def newlead(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        age = request.POST['age']
        city = request.POST['city']
        country = request.POST['country']
        email = request.POST['email']
        agent = request.POST['agent']
        status = request.POST['status']
        lead = Lead(
            first_name = first_name,
            last_name = last_name,
            age = age,
            city = city,
            country = country,
            email = email,
            status = status,
        )
        lead.save()
    return redirect('/leads')

@csrf_exempt
def lead_details(request, pk):
    # print(pk)
    lead = Lead.objects.get(id=pk)
    serializer = LeadSerializer(lead)
    return JsonResponse(serializer.data, safe = False)

@csrf_exempt
def lead_update(request, pk):
    # print(pk)
    lead = Lead.objects.get(id=pk)
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        age = request.POST['age']
        city = request.POST['city']
        country = request.POST['country']
        email = request.POST['email']
        status = request.POST['status']
        lead.first_name = first_name
        lead.last_name = last_name
        lead.age = age
        lead.city = city
        lead.country = country
        lead.email = email
        lead.status = status
        lead.save()
    return redirect('/leads')

@csrf_exempt
def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/leads')



###################
#### Templates ####
###################



###################  
### Class Views ###
###################

### List View

class LeadList(LoginRequiredMixin, generic.ListView):
    template_name = "leads.html"
    
    def get_queryset(self):
        user = self.request.user
        if user.is_company:
            queryset = Lead.objects.filter(company=user.userprofile)
        else:
            queryset = Lead.objects.filter(company=user.agent.company)
            queryset = queryset.filter(agent__user=user)
        return queryset
    # print(queryset)
    context_object_name = "leads" ### It is used to change name the template will take. If changed HTML variable needs to be changed. Default name "object_list"
  
### Detail View      

class LeadDetailView(LoginRequiredMixin, generic.DetailView, generic.CreateView):
    template_name = "onelead.html"
    form_class = LeadDetailForm

    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        if user.is_company:
            queryset = Lead.objects.filter(company=user.userprofile)
        else:
            queryset = Lead.objects.filter(company=user.agent.company)
            queryset = queryset.filter(agent__user=user)
        return queryset


    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        user = self.kwargs.get('pk') # returns partucular user
        context['leadinfo'] = LeadDetail.objects.filter(Lead_id=user)
        return context

    def get_success_url(self):
        # return "/all"
        return reverse("leads:all")

### Create View

class LeadCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "create.html"
    # queryset = Lead.objects.all()
    form_class = LeadForm
    context_object_name = "lead"

    def get_success_url(self):
        # return "/all"
        return reverse("leads:all")


### Update View

class LeadUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = "leadupdate.html"
    queryset = Lead.objects.all()
    form_class = LeadForm
    context_object_name = "lead"

    def get_success_url(self):
        # return "/all"
        return reverse("leads:all")


### Delete View

class LeadDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'delete.html'
    queryset = Lead.objects.all()

    def get_success_url(self):
        # return "/all"
        return reverse("leads:all")


### Signup View

class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    # queryset = Lead.objects.all()
    form_class = CustomUserCreationForm
    context_object_name = "lead"

    def get_success_url(self):
        # return "/all"
        return reverse("leads:login")



######################  
### Function Views ###
######################


### List View

def all(request):
    lead_list = Lead.objects.all() # returns Query set 
    return render(request, "leads.html", {'leads': lead_list})

### Detail View

def eachlead(request, pk):
    # print(pk)
    lead = Lead.objects.get(id=pk)
    leadinfo = LeadDetail.objects.filter(Lead_id=lead).values() # returns JSON
    print(lead.first_name)
    # print(list(leadinfo)) 
    form = LeadDetailForm()
    if request.method == 'POST':
        form = LeadDetailForm(request.POST, request.FILES)
        # print(form.data)
        if form.is_valid():
            lead = lead.first_name
            form.save()
        return redirect('/all')
    return render(request, "onelead.html", {'lead': lead, 'leadinfo': leadinfo, 'form': LeadDetailForm})

### Create View

def create_lead(request):
    form = LeadForm()
    if request.method == 'POST':
        form = LeadForm(request.POST, request.FILES)
        # print(form.data)
        if form.is_valid():
            form.save()
        return redirect('/all')
    return render(request, 'create.html', {'form': LeadForm})


### Update View

def update_lead(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadForm(instance=lead)
    if request.method == 'POST':
        form = LeadForm(request.POST, request.FILES, instance=lead)
        if form.is_valid():
            form.save()
            return redirect('/all')
    return render(request, "leadupdate.html", {'lead': lead, 'form': LeadForm})

### Delete View

def delete_lead(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/all')

crm/templates/agentcreate.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>

{% endblock %}

crm/templates/agentdelete.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h1>Are you sure you want to delete this agent?</h1>
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
    </form>
</div>
{% endblock %}

crm/templates/agentdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
      <img class="object-cover object-center rounded" alt="hero" src="/media/{{lead.avatar}}">
    </div>
    <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">{{agent.user.username}} {{agent.user.last_name}}
        <br class="hidden lg:inline-block">{{agent.user.email}} {{agent.user.last_name}}
      </h1>
      <div class="flex justify-center">
        <a href="/agent/{{agent.pk}}/update"><button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg" type="submit">Edit</button></a>
        <a href="/agent/{{agent.pk}}/delete"><button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Delete</button></a>
      </div>
    </div>
  </div>
  <div>
    <form method="POST" action="/lead/{{lead.pk}}" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
  </form>
  </div>
</section>

{% endblock %}

crm/templates/agents.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'agents:agents-create' %}">Create Agent</a>
{% for agent in object_list %}
      <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-800 sm:flex-row flex-col">
        <div class="sm:w-32 sm:h-32 h-20 w-20 sm:mr-10 inline-flex items-center justify-center rounded-full text-indigo-400 bg-gray-800 flex-shrink-0">
            <img src="" alt=""/>
        </div>
        <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
            <a href="{% url 'agents:agent-detail' agent.pk %}">
                <h2 class="text-black text-lg title-font font-medium mb-2">{{agent.user.username}} {{agent.user.last_name}}</h2>
                <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            </a>
        </div>
      </div>
{% endfor %}

{% endblock %}

crm/templates/agentupdate.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h1>Update User: {{agent.user.username}}</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock %}

crm/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous"> -->
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/static/style.css" />
    <title>CRM</title>
</head>
<body>

    <nav class="bg-white dark:bg-gray-800 shadow">
        <div class="container mx-auto px-6 py-3 md:flex">
            <div class="flex justify-between items-center">
                <div>
                    <a class="text-gray-800 dark:text-white text-xl font-bold md:text-2xl hover:text-gray-700 dark:hover:text-gray-300" href="#">CRM</a>
                </div>
                
                <!-- Mobile menu button -->
                <div class="flex md:hidden">
                    <button type="button" class="text-gray-500 dark:text-gray-200 hover:text-gray-600 dark:hover:text-gray-400 focus:outline-none focus:text-gray-600 dark:focus:text-gray-400" aria-label="toggle menu">
                        <svg viewBox="0 0 24 24" class="h-6 w-6 fill-current">
                            <path fill-rule="evenodd" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"></path>
                        </svg>
                    </button>
                </div>
            </div>

            <!-- Mobile Menu open: "block", Menu closed: "hidden" -->
            <div class="w-full hidden md:flex md:items-center md:justify-between">
                <div class="flex flex-col -mx-4 px-2 py-3 md:flex-row md:mx-0 md:py-0">
                    <a href="/" class="py-1 px-2 text-gray-700 dark:text-gray-200 rounded text-sm font-medium hover:bg-gray-900 hover:text-gray-100 md:mx-2">Home</a>
                    <a href="{% url 'leads:all' %}" class="py-1 px-2 text-gray-700 dark:text-gray-200 rounded text-sm font-medium hover:bg-gray-900 hover:text-gray-100 md:mx-2">Leads</a>
                    <a href="#" class="py-1 px-2 text-gray-700 dark:text-gray-200 rounded text-sm font-medium hover:bg-gray-900 hover:text-gray-100 md:mx-2">Contact</a>
                </div>
                {% if request.user.is_authenticated %}
                Logged in as: {{request.user.email}}
                <a href="{%url 'leads:logout'%}">
                    <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </button>
                </a>
                {% else %}
                <a href="{%url 'leads:login'%}">
                    <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </button>
                </a>
                <a href="{%url 'leads:signup'%}">
                    <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Signup
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </button>
                </a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %} 
    
</body>

</html>

crm/templates/create.html
{% extends 'base.html' %}

{% block content %}
{{ form.errors }}
<form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>

{% endblock %}

crm/templates/delete.html
<div>
    <h1>Are you sure you want to delete this lead?</h1>
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
    </form>
</div>

crm/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Home Page</h1>
{% endblock %}

crm/templates/leads.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
    <div class="container px-5 py-24 mx-auto">
       <a href="{% url 'leads:create-lead' %}">Create Lead</a>
{% for lead in leads %}
      <div class="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-800 sm:flex-row flex-col">
        <div class="sm:w-32 sm:h-32 h-20 w-20 sm:mr-10 inline-flex items-center justify-center rounded-full text-indigo-400 bg-gray-800 flex-shrink-0">
            <img src="/media/{{lead.avatar}}" alt=""/>
        </div>
        <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
            <a href="/lead/{{lead.pk}}">
                <h2 class="text-white text-lg title-font font-medium mb-2">{{lead.first_name}} {{lead.last_name}}</h2>
                <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
            </a>
        </div>
      </div>
{% endfor %}
    </div>
</section>
{% endblock content %}

crm/templates/leadupdate.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h1>Update User: {{lead.first_name}} {{lead.last_name}} </h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Submit</button>
    </form>
</div>

{% endblock %}

crm/templates/onelead.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="text-gray-400 bg-gray-900 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 md:mb-0 mb-10">
      <img class="object-cover object-center rounded" alt="hero" src="/media/{{lead.avatar}}">
    </div>
    <div class="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">{{lead.first_name}} {{lead.last_name}}
        <br class="hidden lg:inline-block">{{lead.status}}
      </h1>
      <p class="mb-8 leading-relaxed">{{lead.city}} {{lead.country}} {{lead.email}}</p>
      {% for eachlead in leadinfo %}
      <p class="mb-8 leading-relaxed">Tasks: {{eachlead.tasks}}</p>
      <a href="/media/{{eachlead.files}}" target="_blank">Files:  {{eachlead.files}} </a>
      {% endfor %}
      <div class="flex justify-center">
        <a href="/lead/{{lead.pk}}/update"><button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg" type="submit">Edit</button></a>
        <a href="/lead/{{lead.pk}}/delete"><button class="ml-4 inline-flex text-gray-400 bg-gray-800 border-0 py-2 px-6 focus:outline-none hover:bg-gray-700 hover:text-white rounded text-lg">Delete</button></a>
      </div>
    </div>
  </div>
  <div>
    <form method="POST" action="/lead/{{lead.pk}}" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
  </form>
  </div>
</section>

{% endblock %}